# Generated by Django 4.2.5 on 2023-10-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormRequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='synopsis',
        ),
    ]
