# Generated by Django 4.2.5 on 2023-10-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_buku'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buku',
            new_name='RequestBook',
        ),
    ]
