# Generated by Django 4.2.5 on 2023-10-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_buku_requestbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestBook',
        ),
    ]
