# Generated by Django 4.2.5 on 2023-10-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usermenu_authors_usermenu_average_rating_and_more'),
        ('main', '0004_delete_requestbook'),
    ]

    operations = [
    ]
