# Generated by Django 4.2.6 on 2023-10-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231026_1608'),
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookuser',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='bookuser',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='bookuser',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='bookuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bookuser',
            name='num_pages',
        ),
        migrations.RemoveField(
            model_name='bookuser',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bookuser',
            name='published_year',
        ),
        migrations.RemoveField(
            model_name='bookuser',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='bookuser',
            name='title',
        ),
        migrations.AddField(
            model_name='bookuser',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
            preserve_default=False,
        ),
    ]
