# Generated by Django 4.2.6 on 2023-10-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='date',
            new_name='birthday',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='job',
        ),
    ]
